"""The SELECT every admin job read starts from: metadata columns and attempt totals."""

ADMIN_JOB_SELECT = (
    "SELECT j.id, j.queue, j.producer, j.kind, j.model, j.priority, j.state, j.privacy, j.tier,"
    " j.created, j.updated, j.finished, j.deadline, j.lease_node, j.lease_expires,"
    " j.parent_id, j.preemptions, j.error, j.acked, j.retry_of,"
    " (SELECT count(*) FROM attempts a WHERE a.job_id=j.id) attempt_count,"
    " (SELECT sum(a.tokens_in) FROM attempts a WHERE a.job_id=j.id) tokens_in,"
    " (SELECT sum(a.tokens_out) FROM attempts a WHERE a.job_id=j.id) tokens_out,"
    " (SELECT sum(a.cost_usd) FROM attempts a WHERE a.job_id=j.id) cost_usd,"
    " (SELECT sum(a.wall_s) FROM attempts a WHERE a.job_id=j.id) wall_s,"
    " (SELECT a.model FROM attempts a WHERE a.job_id=j.id"
    " ORDER BY a.started DESC, a.id DESC LIMIT 1) last_model,"
    " (SELECT a.provider FROM attempts a WHERE a.job_id=j.id"
    " ORDER BY a.started DESC, a.id DESC LIMIT 1) last_provider,"
    " (SELECT a.started FROM attempts a WHERE a.job_id=j.id"
    " ORDER BY a.started DESC, a.id DESC LIMIT 1) last_started,"
    " (SELECT a.outcome FROM attempts a WHERE a.job_id=j.id"
    " ORDER BY a.started DESC, a.id DESC LIMIT 1) last_outcome"
    " FROM jobs j"
)
